wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713497537.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 23
      4: 3.12.3
      5: 0.16.6
      6: 4.40.0
      8:
      - 1
      - 5
      13: darwin-arm64
